name: Test Modified Python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CPython
        run: |
          ./configure
          make -j2

      - name: Test Modified Python
        run: |
          ./python -c "print(0 ** 0)"
          ./python -c "print(2 ** 3)"
          ./python -c "print(0 ** 2)"
